on: [push, pull_request]

jobs:
  test:
    name: Test Homebrew install
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install macFUSE
        run: brew install --cask macfuse

      # - name: Debug
      #   uses: mxschmitt/action-tmate@v3

      - name: Test formula
        working-directory: ./Formula
        run: |
          # brew audit --strict borgbackup-fuse.rb
          brew install borgbackup-fuse.rb
          brew test borgbackup-fuse.rb

      - name: Test mount command
        run: |
          borg init -e none test-repo
          borg create test-repo::test-archive Formula
          # Will timeout due to macOS security prompt
          # mkdir mnt
          # borg mount test-repo::test-archive mnt
          # ls mnt/Formula

